stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.10
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python manage.py check
    - python manage.py test

deploy_to_railway:
  stage: deploy
  image: ubuntu
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
  script:
    - railway up --service=$RAILWAY_SERVICE_NAME -d
  only:
    - main
